### ISSUE TITLE
"Error relocating" when requiring node-relay-exp pre-compiled module with node v8.12.0

### ISSUE THREAD

**Issue by AVapps** [OnionIoT/i2c-exp-node-addons#2]
Requiring "node-relay-exp" either from opkg package or using the pre-compiled file from this repo gives me this error (node v8.12.0) :
```
var relayExp = require('node-relay-exp')
Error: Error relocating /root/garage/node_modules/node-relay-exp.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEi: symbol not found
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Comment by greenbreakfast** [comment]
This module is compiled for Node v4.3.1 - the version the LEDE 17.01 build system is able to compile.
I assume you've installed Node v8.12.0 from other sources?

**Comment by AVapps** [comment]
Yes that's right, I managed to cross compile Node v8 for Omega 2.

**Comment by greenbreakfast** [comment]
Ok, then that's the issue. This is compiled for Node v4.3.1 and it looks like there's some incompatibilities with the Node version you're running. 
Can you try it out with Node 4.3.1?
